"""
Models package - re-exports all models for backward compatibility.
Import order matters: load base models before those that reference them via Relationship.
"""

from sqlmodel import SQLModel

# Auth and user
from app.models.auth import Message, NewPassword, Token, TokenPayload
from app.models.boat import (
    Boat,
    BoatBase,
    BoatCreate,
    BoatPricing,
    BoatPricingBase,
    BoatPricingCreate,
    BoatPricingPublic,
    BoatPricingUpdate,
    BoatPublic,
    BoatsPublic,
    BoatUpdate,
)
from app.models.booking import (
    Booking,
    BookingBase,
    BookingCreate,
    BookingDraftUpdate,
    BookingExperienceDisplay,
    BookingItem,
    BookingItemBase,
    BookingItemCreate,
    BookingItemPublic,
    BookingItemQuantityUpdate,
    BookingItemUpdate,
    BookingPublic,
    BookingUpdate,
    _validate_name_part,
)

# Discount and booking (booking references discount via string)
from app.models.discount import (
    DiscountCode,
    DiscountCodeBase,
    DiscountCodeCreate,
    DiscountCodePublic,
    DiscountCodeUpdate,
)

# Enums first (no dependencies)
from app.models.enums import (
    BookingItemStatus,
    BookingMode,
    BookingStatus,
    DiscountCodeType,
    PaymentStatus,
)
from app.models.jurisdiction import (
    Jurisdiction,
    JurisdictionBase,
    JurisdictionCreate,
    JurisdictionPublic,
    JurisdictionsPublic,
    JurisdictionUpdate,
)

# Launch and mission
from app.models.launch import (
    Launch,
    LaunchBase,
    LaunchCreate,
    LaunchesPublic,
    LaunchPublic,
    LaunchUpdate,
)

# Location and jurisdiction
from app.models.location import (
    Location,
    LocationBase,
    LocationCreate,
    LocationPublic,
    LocationsPublic,
    LocationUpdate,
)

# Merchandise and trip_merchandise
from app.models.merchandise import (
    Merchandise,
    MerchandiseBase,
    MerchandiseCreate,
    MerchandisePublic,
    MerchandisesPublic,
    MerchandiseUpdate,
    MerchandiseVariation,
    MerchandiseVariationBase,
    MerchandiseVariationCreate,
    MerchandiseVariationPublic,
    MerchandiseVariationUpdate,
)
from app.models.mission import (
    Mission,
    MissionBase,
    MissionCreate,
    MissionPublic,
    MissionsPublic,
    MissionsWithStatsPublic,
    MissionUpdate,
    MissionWithStats,
)

# Provider and boat
from app.models.provider import (
    Provider,
    ProviderBase,
    ProviderCreate,
    ProviderPublic,
    ProvidersPublic,
    ProviderUpdate,
)

# Trip and trip_boat
from app.models.trip import (
    PublicTripsResponse,
    Trip,
    TripBase,
    TripBoatCreateItem,
    TripBoatPricingCreateItem,
    TripCreate,
    TripCreateFull,
    TripMerchandiseCreateItem,
    TripPublic,
    TripsPublic,
    TripsWithStatsPublic,
    TripUpdate,
    TripWithStats,
)
from app.models.trip_boat import (
    EffectivePricingItem,
    TripBoat,
    TripBoatBase,
    TripBoatCreate,
    TripBoatPricing,
    TripBoatPricingBase,
    TripBoatPricingCreate,
    TripBoatPricingPublic,
    TripBoatPricingUpdate,
    TripBoatPublic,
    TripBoatPublicWithAvailability,
    TripBoatUpdate,
)
from app.models.trip_merchandise import (
    TripMerchandise,
    TripMerchandiseBase,
    TripMerchandiseCreate,
    TripMerchandisePublic,
    TripMerchandiseUpdate,
    TripMerchandiseVariationAvailability,
)
from app.models.user import (
    UpdatePassword,
    User,
    UserBase,
    UserCreate,
    UserPublic,
    UserRegister,
    UsersPublic,
    UserUpdate,
    UserUpdateMe,
)

__all__ = [
    "Booking",
    "BookingBase",
    "BookingCreate",
    "BookingDraftUpdate",
    "BookingExperienceDisplay",
    "BookingItem",
    "BookingItemBase",
    "BookingItemCreate",
    "BookingItemPublic",
    "BookingItemQuantityUpdate",
    "BookingItemStatus",
    "BookingItemUpdate",
    "BookingMode",
    "BookingPublic",
    "BookingStatus",
    "BookingUpdate",
    "Boat",
    "BoatBase",
    "BoatCreate",
    "BoatPricing",
    "BoatPricingBase",
    "BoatPricingCreate",
    "BoatPricingPublic",
    "BoatPricingUpdate",
    "BoatPublic",
    "BoatsPublic",
    "BoatUpdate",
    "DiscountCode",
    "DiscountCodeBase",
    "DiscountCodeCreate",
    "DiscountCodePublic",
    "DiscountCodeType",
    "DiscountCodeUpdate",
    "EffectivePricingItem",
    "Launch",
    "LaunchBase",
    "LaunchCreate",
    "LaunchPublic",
    "LaunchesPublic",
    "LaunchUpdate",
    "Location",
    "LocationBase",
    "LocationCreate",
    "LocationPublic",
    "LocationsPublic",
    "LocationUpdate",
    "Message",
    "Merchandise",
    "MerchandiseBase",
    "MerchandiseCreate",
    "MerchandisePublic",
    "MerchandisesPublic",
    "MerchandiseUpdate",
    "MerchandiseVariation",
    "MerchandiseVariationBase",
    "MerchandiseVariationCreate",
    "MerchandiseVariationPublic",
    "MerchandiseVariationUpdate",
    "Mission",
    "MissionBase",
    "MissionCreate",
    "MissionPublic",
    "MissionsPublic",
    "MissionsWithStatsPublic",
    "MissionUpdate",
    "MissionWithStats",
    "NewPassword",
    "PaymentStatus",
    "Provider",
    "ProviderBase",
    "ProviderCreate",
    "ProviderPublic",
    "ProvidersPublic",
    "ProviderUpdate",
    "PublicTripsResponse",
    "SQLModel",
    "Token",
    "TokenPayload",
    "Trip",
    "TripBase",
    "TripBoat",
    "TripBoatBase",
    "TripBoatCreate",
    "TripBoatCreateItem",
    "TripBoatPricing",
    "TripBoatPricingBase",
    "TripBoatPricingCreate",
    "TripBoatPricingCreateItem",
    "TripBoatPricingPublic",
    "TripBoatPricingUpdate",
    "TripBoatPublic",
    "TripBoatPublicWithAvailability",
    "TripBoatUpdate",
    "TripCreate",
    "TripCreateFull",
    "TripMerchandise",
    "TripMerchandiseBase",
    "TripMerchandiseCreate",
    "TripMerchandiseCreateItem",
    "TripMerchandisePublic",
    "TripMerchandiseUpdate",
    "TripMerchandiseVariationAvailability",
    "TripPublic",
    "TripsPublic",
    "TripsWithStatsPublic",
    "TripUpdate",
    "TripWithStats",
    "UpdatePassword",
    "User",
    "UserBase",
    "UserCreate",
    "UserPublic",
    "UsersPublic",
    "UserRegister",
    "UserUpdate",
    "UserUpdateMe",
    "Jurisdiction",
    "JurisdictionBase",
    "JurisdictionCreate",
    "JurisdictionPublic",
    "JurisdictionsPublic",
    "JurisdictionUpdate",
    "_validate_name_part",
]
