// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise"
import { OpenAPI } from "./core/OpenAPI"
import { request as __request } from "./core/request"
import type {
  BoatsReadBoatsData,
  BoatsReadBoatsResponse,
  BoatsCreateBoatData,
  BoatsCreateBoatResponse,
  BoatsReadBoatData,
  BoatsReadBoatResponse,
  BoatsUpdateBoatData,
  BoatsUpdateBoatResponse,
  BoatsDeleteBoatData,
  BoatsDeleteBoatResponse,
  BoatsReadBoatsByJurisdictionData,
  BoatsReadBoatsByJurisdictionResponse,
  BoatsReadPublicBoatData,
  BoatsReadPublicBoatResponse,
  BoatsReadPublicBoatsData,
  BoatsReadPublicBoatsResponse,
  BookingsCreateBookingData,
  BookingsCreateBookingResponse,
  BookingsListBookingsData,
  BookingsListBookingsResponse,
  BookingsGetBookingByIdData,
  BookingsGetBookingByIdResponse,
  BookingsUpdateBookingData,
  BookingsUpdateBookingResponse,
  BookingsCheckInBookingData,
  BookingsCheckInBookingResponse,
  BookingPublicResendBookingConfirmationEmailData,
  BookingPublicResendBookingConfirmationEmailResponse,
  BookingsProcessRefundData,
  BookingsProcessRefundResponse,
  BookingsExportBookingsCsvData,
  BookingsExportBookingsCsvResponse,
  BookingsGetBookingQrCodeData,
  BookingsGetBookingQrCodeResponse,
  BookingsGetBookingByConfirmationCodeData,
  BookingsGetBookingByConfirmationCodeResponse,
  BookingsInitializePaymentData,
  BookingsInitializePaymentResponse,
  BookingsResumePaymentData,
  BookingsResumePaymentResponse,
  DiscountCodesCreateDiscountCodeData,
  DiscountCodesCreateDiscountCodeResponse,
  DiscountCodesListDiscountCodesData,
  DiscountCodesListDiscountCodesResponse,
  DiscountCodesGetDiscountCodeData,
  DiscountCodesGetDiscountCodeResponse,
  DiscountCodesUpdateDiscountCodeData,
  DiscountCodesUpdateDiscountCodeResponse,
  DiscountCodesDeleteDiscountCodeData,
  DiscountCodesDeleteDiscountCodeResponse,
  DiscountCodesValidateDiscountCodeData,
  DiscountCodesValidateDiscountCodeResponse,
  DiscountCodesValidateAccessCodeData,
  DiscountCodesValidateAccessCodeResponse,
  ImportImportYamlDocumentData,
  ImportImportYamlDocumentResponse,
  JurisdictionsReadPublicJurisdictionsData,
  JurisdictionsReadPublicJurisdictionsResponse,
  JurisdictionsReadJurisdictionsData,
  JurisdictionsReadJurisdictionsResponse,
  JurisdictionsCreateJurisdictionData,
  JurisdictionsCreateJurisdictionResponse,
  JurisdictionsReadJurisdictionData,
  JurisdictionsReadJurisdictionResponse,
  JurisdictionsUpdateJurisdictionData,
  JurisdictionsUpdateJurisdictionResponse,
  JurisdictionsDeleteJurisdictionData,
  JurisdictionsDeleteJurisdictionResponse,
  LaunchesReadLaunchesData,
  LaunchesReadLaunchesResponse,
  LaunchesCreateLaunchData,
  LaunchesCreateLaunchResponse,
  LaunchesReadLaunchData,
  LaunchesReadLaunchResponse,
  LaunchesUpdateLaunchData,
  LaunchesUpdateLaunchResponse,
  LaunchesDeleteLaunchData,
  LaunchesDeleteLaunchResponse,
  LaunchesReadLaunchesByLocationData,
  LaunchesReadLaunchesByLocationResponse,
  LaunchesReadPublicLaunchesData,
  LaunchesReadPublicLaunchesResponse,
  LaunchesReadPublicLaunchData,
  LaunchesReadPublicLaunchResponse,
  LaunchesImportLaunchFromYamlData,
  LaunchesImportLaunchFromYamlResponse,
  LaunchesSendLaunchUpdateData,
  LaunchesSendLaunchUpdateResponse,
  LocationsReadLocationsData,
  LocationsReadLocationsResponse,
  LocationsCreateLocationData,
  LocationsCreateLocationResponse,
  LocationsReadLocationData,
  LocationsReadLocationResponse,
  LocationsUpdateLocationData,
  LocationsUpdateLocationResponse,
  LocationsDeleteLocationData,
  LocationsDeleteLocationResponse,
  LoginLoginAccessTokenData,
  LoginLoginAccessTokenResponse,
  LoginTestTokenResponse,
  LoginRecoverPasswordData,
  LoginRecoverPasswordResponse,
  LoginResetPasswordData,
  LoginResetPasswordResponse,
  LoginRecoverPasswordHtmlContentData,
  LoginRecoverPasswordHtmlContentResponse,
  MerchandiseReadMerchandiseListData,
  MerchandiseReadMerchandiseListResponse,
  MerchandiseCreateMerchandiseData,
  MerchandiseCreateMerchandiseResponse,
  MerchandiseReadMerchandiseData,
  MerchandiseReadMerchandiseResponse,
  MerchandiseUpdateMerchandiseData,
  MerchandiseUpdateMerchandiseResponse,
  MerchandiseDeleteMerchandiseData,
  MerchandiseDeleteMerchandiseResponse,
  MissionsReadMissionsData,
  MissionsReadMissionsResponse,
  MissionsCreateMissionData,
  MissionsCreateMissionResponse,
  MissionsReadMissionData,
  MissionsReadMissionResponse,
  MissionsUpdateMissionData,
  MissionsUpdateMissionResponse,
  MissionsDeleteMissionData,
  MissionsDeleteMissionResponse,
  MissionsReadMissionsByLaunchData,
  MissionsReadMissionsByLaunchResponse,
  MissionsReadActiveMissionsData,
  MissionsReadActiveMissionsResponse,
  MissionsReadPublicMissionsData,
  MissionsReadPublicMissionsResponse,
  MissionsImportMissionFromYamlData,
  MissionsImportMissionFromYamlResponse,
  PaymentsCreatePaymentIntentEndpointData,
  PaymentsCreatePaymentIntentEndpointResponse,
  PaymentsVerifyPaymentData,
  PaymentsVerifyPaymentResponse,
  PaymentsStripeWebhookResponse,
  PrivateCreateUserData,
  PrivateCreateUserResponse,
  ProvidersReadPublicProvidersData,
  ProvidersReadPublicProvidersResponse,
  ProvidersReadProvidersData,
  ProvidersReadProvidersResponse,
  ProvidersCreateProviderData,
  ProvidersCreateProviderResponse,
  ProvidersReadProviderData,
  ProvidersReadProviderResponse,
  ProvidersUpdateProviderData,
  ProvidersUpdateProviderResponse,
  ProvidersDeleteProviderData,
  ProvidersDeleteProviderResponse,
  ProvidersReadProvidersByJurisdictionData,
  ProvidersReadProvidersByJurisdictionResponse,
  ProvidersReadPublicProviderData,
  ProvidersReadPublicProviderResponse,
  TripBoatsCreateTripBoatData,
  TripBoatsCreateTripBoatResponse,
  TripBoatsReadTripBoatsByTripData,
  TripBoatsReadTripBoatsByTripResponse,
  TripBoatsReadTripBoatsByBoatData,
  TripBoatsReadTripBoatsByBoatResponse,
  TripBoatsUpdateTripBoatData,
  TripBoatsUpdateTripBoatResponse,
  TripBoatsDeleteTripBoatData,
  TripBoatsDeleteTripBoatResponse,
  TripBoatsReadPublicTripBoatsByTripData,
  TripBoatsReadPublicTripBoatsByTripResponse,
  TripMerchandiseCreateTripMerchandiseData,
  TripMerchandiseCreateTripMerchandiseResponse,
  TripMerchandiseListTripMerchandiseData,
  TripMerchandiseListTripMerchandiseResponse,
  TripMerchandiseGetTripMerchandiseData,
  TripMerchandiseGetTripMerchandiseResponse,
  TripMerchandiseUpdateTripMerchandiseData,
  TripMerchandiseUpdateTripMerchandiseResponse,
  TripMerchandiseDeleteTripMerchandiseData,
  TripMerchandiseDeleteTripMerchandiseResponse,
  TripMerchandiseListPublicTripMerchandiseData,
  TripMerchandiseListPublicTripMerchandiseResponse,
  TripPricingCreateTripPricingData,
  TripPricingCreateTripPricingResponse,
  TripPricingListTripPricingData,
  TripPricingListTripPricingResponse,
  TripPricingGetTripPricingData,
  TripPricingGetTripPricingResponse,
  TripPricingUpdateTripPricingData,
  TripPricingUpdateTripPricingResponse,
  TripPricingDeleteTripPricingData,
  TripPricingDeleteTripPricingResponse,
  TripPricingListPublicTripPricingData,
  TripPricingListPublicTripPricingResponse,
  TripsReadTripsData,
  TripsReadTripsResponse,
  TripsCreateTripData,
  TripsCreateTripResponse,
  TripsReadTripData,
  TripsReadTripResponse,
  TripsUpdateTripData,
  TripsUpdateTripResponse,
  TripsDeleteTripData,
  TripsDeleteTripResponse,
  TripsReadTripsByMissionData,
  TripsReadTripsByMissionResponse,
  TripsReadPublicTripsData,
  TripsReadPublicTripsResponse,
  TripsReadPublicTripData,
  TripsReadPublicTripResponse,
  TripsImportTripFromYamlData,
  TripsImportTripFromYamlResponse,
  UsersReadUsersData,
  UsersReadUsersResponse,
  UsersCreateUserData,
  UsersCreateUserResponse,
  UsersReadUserMeResponse,
  UsersDeleteUserMeResponse,
  UsersUpdateUserMeData,
  UsersUpdateUserMeResponse,
  UsersUpdatePasswordMeData,
  UsersUpdatePasswordMeResponse,
  UsersReadUserByIdData,
  UsersReadUserByIdResponse,
  UsersUpdateUserData,
  UsersUpdateUserResponse,
  UsersDeleteUserData,
  UsersDeleteUserResponse,
  UtilsTestEmailData,
  UtilsTestEmailResponse,
  UtilsHealthCheckResponse,
  UtilsGetUsStatesResponse,
} from "./types.gen"

export class BoatsService {
  /**
   * Read Boats
   * Retrieve boats.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns BoatsPublic Successful Response
   * @throws ApiError
   */
  public static readBoats(
    data: BoatsReadBoatsData = {},
  ): CancelablePromise<BoatsReadBoatsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/boats/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Boat
   * Create new boat.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns BoatPublic Successful Response
   * @throws ApiError
   */
  public static createBoat(
    data: BoatsCreateBoatData,
  ): CancelablePromise<BoatsCreateBoatResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/boats/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Boat
   * Get boat by ID.
   * @param data The data for the request.
   * @param data.boatId
   * @returns BoatPublic Successful Response
   * @throws ApiError
   */
  public static readBoat(
    data: BoatsReadBoatData,
  ): CancelablePromise<BoatsReadBoatResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/boats/{boat_id}",
      path: {
        boat_id: data.boatId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Boat
   * Update a boat.
   * @param data The data for the request.
   * @param data.boatId
   * @param data.requestBody
   * @returns BoatPublic Successful Response
   * @throws ApiError
   */
  public static updateBoat(
    data: BoatsUpdateBoatData,
  ): CancelablePromise<BoatsUpdateBoatResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/boats/{boat_id}",
      path: {
        boat_id: data.boatId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Boat
   * Delete a boat.
   * @param data The data for the request.
   * @param data.boatId
   * @returns void Successful Response
   * @throws ApiError
   */
  public static deleteBoat(
    data: BoatsDeleteBoatData,
  ): CancelablePromise<BoatsDeleteBoatResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/boats/{boat_id}",
      path: {
        boat_id: data.boatId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Boats By Jurisdiction
   * Retrieve boats for a specific jurisdiction.
   * @param data The data for the request.
   * @param data.jurisdictionId
   * @param data.skip
   * @param data.limit
   * @returns BoatsPublic Successful Response
   * @throws ApiError
   */
  public static readBoatsByJurisdiction(
    data: BoatsReadBoatsByJurisdictionData,
  ): CancelablePromise<BoatsReadBoatsByJurisdictionResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/boats/jurisdiction/{jurisdiction_id}",
      path: {
        jurisdiction_id: data.jurisdictionId,
      },
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Public Boat
   * Get boat by ID for public booking form.
   * No authentication required.
   * @param data The data for the request.
   * @param data.boatId
   * @returns BoatPublic Successful Response
   * @throws ApiError
   */
  public static readPublicBoat(
    data: BoatsReadPublicBoatData,
  ): CancelablePromise<BoatsReadPublicBoatResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/boats/public/{boat_id}",
      path: {
        boat_id: data.boatId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Public Boats
   * Retrieve boats for public booking form.
   * No authentication required.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns BoatsPublic Successful Response
   * @throws ApiError
   */
  public static readPublicBoats(
    data: BoatsReadPublicBoatsData = {},
  ): CancelablePromise<BoatsReadPublicBoatsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/boats/public/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class BookingsService {
  /**
   * Create Booking
   * Create new booking (authentication optional - public or admin).
   * @param data The data for the request.
   * @param data.requestBody
   * @returns BookingPublic Successful Response
   * @throws ApiError
   */
  public static createBooking(
    data: BookingsCreateBookingData,
  ): CancelablePromise<BookingsCreateBookingResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/bookings/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * List Bookings
   * List/search bookings (admin only).
   * Optionally filter by mission_id.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @param data.missionId
   * @param data.sortBy
   * @param data.sortDirection
   * @returns BookingsPaginatedResponse Successful Response
   * @throws ApiError
   */
  public static listBookings(
    data: BookingsListBookingsData = {},
  ): CancelablePromise<BookingsListBookingsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/bookings/",
      query: {
        skip: data.skip,
        limit: data.limit,
        mission_id: data.missionId,
        sort_by: data.sortBy,
        sort_direction: data.sortDirection,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Booking By Id
   * Retrieve booking details by ID (admin only).
   * @param data The data for the request.
   * @param data.bookingId
   * @returns BookingPublic Successful Response
   * @throws ApiError
   */
  public static getBookingById(
    data: BookingsGetBookingByIdData,
  ): CancelablePromise<BookingsGetBookingByIdResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/bookings/id/{booking_id}",
      path: {
        booking_id: data.bookingId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Booking
   * Update booking status or details (admin only).
   * @param data The data for the request.
   * @param data.bookingId
   * @param data.requestBody
   * @returns BookingPublic Successful Response
   * @throws ApiError
   */
  public static updateBooking(
    data: BookingsUpdateBookingData,
  ): CancelablePromise<BookingsUpdateBookingResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/bookings/id/{booking_id}",
      path: {
        booking_id: data.bookingId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Check In Booking
   * Check in a booking by confirmation code.
   *
   * Validates the booking against the selected trip/boat context and updates
   * the booking status to 'checked_in' and item statuses to 'fulfilled'.
   * @param data The data for the request.
   * @param data.confirmationCode
   * @param data.tripId
   * @param data.boatId
   * @returns BookingPublic Successful Response
   * @throws ApiError
   */
  public static checkInBooking(
    data: BookingsCheckInBookingData,
  ): CancelablePromise<BookingsCheckInBookingResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/bookings/check-in/{confirmation_code}",
      path: {
        confirmation_code: data.confirmationCode,
      },
      query: {
        trip_id: data.tripId,
        boat_id: data.boatId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Resend Booking Confirmation Email
   * Resend booking confirmation email.
   *
   * Args:
   * confirmation_code: The booking confirmation code
   *
   * Returns:
   * dict: Status of the email sending
   * @param data The data for the request.
   * @param data.confirmationCode
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static bookingPublicResendBookingConfirmationEmail(
    data: BookingPublicResendBookingConfirmationEmailData,
  ): CancelablePromise<BookingPublicResendBookingConfirmationEmailResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/bookings/{confirmation_code}/resend-email",
      path: {
        confirmation_code: data.confirmationCode,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Process Refund
   * Process a refund for a booking.
   *
   * refund_amount_cents: Amount to refund in cents. If None, refunds full booking total.
   * Validates the booking and processes the refund through Stripe,
   * then updates the booking status to 'refunded'.
   * @param data The data for the request.
   * @param data.confirmationCode
   * @param data.refundReason
   * @param data.refundNotes
   * @param data.refundAmountCents
   * @returns BookingPublic Successful Response
   * @throws ApiError
   */
  public static processRefund(
    data: BookingsProcessRefundData,
  ): CancelablePromise<BookingsProcessRefundResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/bookings/refund/{confirmation_code}",
      path: {
        confirmation_code: data.confirmationCode,
      },
      query: {
        refund_reason: data.refundReason,
        refund_notes: data.refundNotes,
        refund_amount_cents: data.refundAmountCents,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Export Bookings Csv
   * Export bookings data to CSV format.
   *
   * Supports filtering by mission_id, trip_id, and booking_status.
   * Supports field selection via the fields parameter (comma-separated list of field names).
   * Available fields: confirmation_code, customer_name, email, phone, billing_address,
   * status, total_amount, subtotal, discount_amount, tax_amount, tip_amount, created_at,
   * trip_type, boat_name; ticket_types (or ticket_types_quantity, ticket_types_price,
   * ticket_types_total); swag (or swag_description, swag_total).
   *
   * When ticket-type columns are requested (ticket_types, ticket_types_quantity, etc.),
   * trip_id should be provided. The ticket-type columns will be derived from that trip's
   * TripPricing records, ensuring consistent column headers that match the trip's configuration.
   * Booking items will be matched to the trip's ticket types (with backward compatibility
   * for legacy naming variants like "adult" vs "adult_ticket").
   * @param data The data for the request.
   * @param data.missionId
   * @param data.tripId
   * @param data.bookingStatus
   * @param data.fields
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static exportBookingsCsv(
    data: BookingsExportBookingsCsvData = {},
  ): CancelablePromise<BookingsExportBookingsCsvResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/bookings/export/csv",
      query: {
        mission_id: data.missionId,
        trip_id: data.tripId,
        booking_status: data.bookingStatus,
        fields: data.fields,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Booking Qr Code
   * Get QR code image for a booking confirmation code.
   * @param data The data for the request.
   * @param data.confirmationCode
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getBookingQrCode(
    data: BookingsGetBookingQrCodeData,
  ): CancelablePromise<BookingsGetBookingQrCodeResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/bookings/qr/{confirmation_code}",
      path: {
        confirmation_code: data.confirmationCode,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Booking By Confirmation Code
   * Retrieve a booking by confirmation code (public endpoint).
   * @param data The data for the request.
   * @param data.confirmationCode
   * @returns BookingPublic Successful Response
   * @throws ApiError
   */
  public static getBookingByConfirmationCode(
    data: BookingsGetBookingByConfirmationCodeData,
  ): CancelablePromise<BookingsGetBookingByConfirmationCodeResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/bookings/{confirmation_code}",
      path: {
        confirmation_code: data.confirmationCode,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Initialize Payment
   * Initialize payment for a draft booking.
   * Creates a PaymentIntent and updates booking status to pending_payment.
   * @param data The data for the request.
   * @param data.confirmationCode
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static initializePayment(
    data: BookingsInitializePaymentData,
  ): CancelablePromise<BookingsInitializePaymentResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/bookings/{confirmation_code}/initialize-payment",
      path: {
        confirmation_code: data.confirmationCode,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Resume Payment
   * Return existing PaymentIntent client_secret for a pending_payment booking.
   * Allows resuming payment without creating a new booking or PaymentIntent.
   * @param data The data for the request.
   * @param data.confirmationCode
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static resumePayment(
    data: BookingsResumePaymentData,
  ): CancelablePromise<BookingsResumePaymentResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/bookings/{confirmation_code}/resume-payment",
      path: {
        confirmation_code: data.confirmationCode,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class DiscountCodesService {
  /**
   * Create Discount Code
   * Create new discount code.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns DiscountCodePublic Successful Response
   * @throws ApiError
   */
  public static createDiscountCode(
    data: DiscountCodesCreateDiscountCodeData,
  ): CancelablePromise<DiscountCodesCreateDiscountCodeResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/discount-codes/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * List Discount Codes
   * Retrieve discount codes.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @param data.isActive
   * @returns DiscountCodePublic Successful Response
   * @throws ApiError
   */
  public static listDiscountCodes(
    data: DiscountCodesListDiscountCodesData = {},
  ): CancelablePromise<DiscountCodesListDiscountCodesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/discount-codes/",
      query: {
        skip: data.skip,
        limit: data.limit,
        is_active: data.isActive,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Discount Code
   * Get discount code by ID.
   * @param data The data for the request.
   * @param data.discountCodeId
   * @returns DiscountCodePublic Successful Response
   * @throws ApiError
   */
  public static getDiscountCode(
    data: DiscountCodesGetDiscountCodeData,
  ): CancelablePromise<DiscountCodesGetDiscountCodeResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/discount-codes/{discount_code_id}",
      path: {
        discount_code_id: data.discountCodeId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Discount Code
   * Update discount code.
   * @param data The data for the request.
   * @param data.discountCodeId
   * @param data.requestBody
   * @returns DiscountCodePublic Successful Response
   * @throws ApiError
   */
  public static updateDiscountCode(
    data: DiscountCodesUpdateDiscountCodeData,
  ): CancelablePromise<DiscountCodesUpdateDiscountCodeResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/discount-codes/{discount_code_id}",
      path: {
        discount_code_id: data.discountCodeId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Discount Code
   * Delete discount code.
   * @param data The data for the request.
   * @param data.discountCodeId
   * @returns string Successful Response
   * @throws ApiError
   */
  public static deleteDiscountCode(
    data: DiscountCodesDeleteDiscountCodeData,
  ): CancelablePromise<DiscountCodesDeleteDiscountCodeResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/discount-codes/{discount_code_id}",
      path: {
        discount_code_id: data.discountCodeId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Validate Discount Code
   * Validate discount code and return details if valid.
   * @param data The data for the request.
   * @param data.code
   * @param data.subtotalCents
   * @returns DiscountCodePublic Successful Response
   * @throws ApiError
   */
  public static validateDiscountCode(
    data: DiscountCodesValidateDiscountCodeData,
  ): CancelablePromise<DiscountCodesValidateDiscountCodeResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/discount-codes/validate/{code}",
      path: {
        code: data.code,
      },
      query: {
        subtotal_cents: data.subtotalCents,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Validate Access Code
   * Validate an access code for early_bird booking mode.
   * Returns validation status and the discount code details if valid.
   * @param data The data for the request.
   * @param data.code
   * @param data.missionId
   * @returns AccessCodeValidationResponse Successful Response
   * @throws ApiError
   */
  public static validateAccessCode(
    data: DiscountCodesValidateAccessCodeData,
  ): CancelablePromise<DiscountCodesValidateAccessCodeResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/discount-codes/validate-access/{code}",
      path: {
        code: data.code,
      },
      query: {
        mission_id: data.missionId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class ImportService {
  /**
   * Import Yaml Document
   * Import launches, missions, and trips from a single YAML file.
   *
   * Root must contain at least one of: launches (list), missions (list), trips (list).
   * Missions may use launch_id (UUID) or launch_ref (0-based index into launches in this file).
   * Trips may use mission_id (UUID) or mission_ref (0-based index into missions in this file).
   * Creation order: launches, then missions, then trips.
   * @param data The data for the request.
   * @param data.formData
   * @returns ImportResult Successful Response
   * @throws ApiError
   */
  public static importYamlDocument(
    data: ImportImportYamlDocumentData,
  ): CancelablePromise<ImportImportYamlDocumentResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/import/yaml",
      formData: data.formData,
      mediaType: "multipart/form-data",
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class JurisdictionsService {
  /**
   * Read Public Jurisdictions
   * Retrieve jurisdictions with optional filtering by location (public endpoint).
   * Used by public booking form to calculate tax rates.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @param data.locationId
   * @returns JurisdictionsPublic Successful Response
   * @throws ApiError
   */
  public static readPublicJurisdictions(
    data: JurisdictionsReadPublicJurisdictionsData = {},
  ): CancelablePromise<JurisdictionsReadPublicJurisdictionsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/jurisdictions/public/",
      query: {
        skip: data.skip,
        limit: data.limit,
        location_id: data.locationId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Jurisdictions
   * Retrieve jurisdictions with optional filtering by location.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @param data.locationId
   * @returns JurisdictionsPublic Successful Response
   * @throws ApiError
   */
  public static readJurisdictions(
    data: JurisdictionsReadJurisdictionsData = {},
  ): CancelablePromise<JurisdictionsReadJurisdictionsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/jurisdictions/",
      query: {
        skip: data.skip,
        limit: data.limit,
        location_id: data.locationId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Jurisdiction
   * Create new jurisdiction.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns JurisdictionPublic Successful Response
   * @throws ApiError
   */
  public static createJurisdiction(
    data: JurisdictionsCreateJurisdictionData,
  ): CancelablePromise<JurisdictionsCreateJurisdictionResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/jurisdictions/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Jurisdiction
   * Get jurisdiction by ID.
   * @param data The data for the request.
   * @param data.jurisdictionId
   * @returns JurisdictionPublic Successful Response
   * @throws ApiError
   */
  public static readJurisdiction(
    data: JurisdictionsReadJurisdictionData,
  ): CancelablePromise<JurisdictionsReadJurisdictionResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/jurisdictions/{jurisdiction_id}",
      path: {
        jurisdiction_id: data.jurisdictionId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Jurisdiction
   * Update a jurisdiction.
   * @param data The data for the request.
   * @param data.jurisdictionId
   * @param data.requestBody
   * @returns JurisdictionPublic Successful Response
   * @throws ApiError
   */
  public static updateJurisdiction(
    data: JurisdictionsUpdateJurisdictionData,
  ): CancelablePromise<JurisdictionsUpdateJurisdictionResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/jurisdictions/{jurisdiction_id}",
      path: {
        jurisdiction_id: data.jurisdictionId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Jurisdiction
   * Delete a jurisdiction.
   * @param data The data for the request.
   * @param data.jurisdictionId
   * @returns void Successful Response
   * @throws ApiError
   */
  public static deleteJurisdiction(
    data: JurisdictionsDeleteJurisdictionData,
  ): CancelablePromise<JurisdictionsDeleteJurisdictionResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/jurisdictions/{jurisdiction_id}",
      path: {
        jurisdiction_id: data.jurisdictionId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class LaunchesService {
  /**
   * Read Launches
   * Retrieve launches.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns LaunchesPublic Successful Response
   * @throws ApiError
   */
  public static readLaunches(
    data: LaunchesReadLaunchesData = {},
  ): CancelablePromise<LaunchesReadLaunchesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/launches/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Launch
   * Create new launch.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns LaunchPublic Successful Response
   * @throws ApiError
   */
  public static createLaunch(
    data: LaunchesCreateLaunchData,
  ): CancelablePromise<LaunchesCreateLaunchResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/launches/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Launch
   * Get launch by ID.
   * @param data The data for the request.
   * @param data.launchId
   * @returns LaunchPublic Successful Response
   * @throws ApiError
   */
  public static readLaunch(
    data: LaunchesReadLaunchData,
  ): CancelablePromise<LaunchesReadLaunchResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/launches/{launch_id}",
      path: {
        launch_id: data.launchId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Launch
   * Update a launch.
   * @param data The data for the request.
   * @param data.launchId
   * @param data.requestBody
   * @param data.allowPastEdit
   * @returns LaunchPublic Successful Response
   * @throws ApiError
   */
  public static updateLaunch(
    data: LaunchesUpdateLaunchData,
  ): CancelablePromise<LaunchesUpdateLaunchResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/launches/{launch_id}",
      path: {
        launch_id: data.launchId,
      },
      query: {
        allow_past_edit: data.allowPastEdit,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Launch
   * Delete a launch.
   * @param data The data for the request.
   * @param data.launchId
   * @returns void Successful Response
   * @throws ApiError
   */
  public static deleteLaunch(
    data: LaunchesDeleteLaunchData,
  ): CancelablePromise<LaunchesDeleteLaunchResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/launches/{launch_id}",
      path: {
        launch_id: data.launchId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Launches By Location
   * Retrieve launches for a specific location.
   * @param data The data for the request.
   * @param data.locationId
   * @param data.skip
   * @param data.limit
   * @returns LaunchesPublic Successful Response
   * @throws ApiError
   */
  public static readLaunchesByLocation(
    data: LaunchesReadLaunchesByLocationData,
  ): CancelablePromise<LaunchesReadLaunchesByLocationResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/launches/location/{location_id}",
      path: {
        location_id: data.locationId,
      },
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Public Launches
   * Retrieve public launches for booking form.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns LaunchesPublic Successful Response
   * @throws ApiError
   */
  public static readPublicLaunches(
    data: LaunchesReadPublicLaunchesData = {},
  ): CancelablePromise<LaunchesReadPublicLaunchesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/launches/public/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Public Launch
   * Get public launch by ID for booking form.
   * @param data The data for the request.
   * @param data.launchId
   * @returns LaunchPublic Successful Response
   * @throws ApiError
   */
  public static readPublicLaunch(
    data: LaunchesReadPublicLaunchData,
  ): CancelablePromise<LaunchesReadPublicLaunchResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/launches/public/{launch_id}",
      path: {
        launch_id: data.launchId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Import Launch From Yaml
   * Import a launch from YAML file.
   *
   * Expected YAML format:
   * ```yaml
   * name: "SpaceX Falcon 9 - Starlink Group 6-1"
   * launch_timestamp: "2024-06-15T18:45:00Z"
   * summary: "Brief description of the launch."
   * location_id: "uuid-of-existing-location"
   * ```
   * @param data The data for the request.
   * @param data.formData
   * @returns LaunchPublic Successful Response
   * @throws ApiError
   */
  public static importLaunchFromYaml(
    data: LaunchesImportLaunchFromYamlData,
  ): CancelablePromise<LaunchesImportLaunchFromYamlResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/launches/import-yaml",
      formData: data.formData,
      mediaType: "multipart/form-data",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Send Launch Update
   * Send a launch update email to all customers with confirmed bookings
   * for this launch who have opted in to receive launch updates.
   *
   * If priority is True, sends to all customers regardless of their
   * launch_updates_pref setting.
   * @param data The data for the request.
   * @param data.launchId
   * @param data.requestBody
   * @returns LaunchUpdateResponse Successful Response
   * @throws ApiError
   */
  public static sendLaunchUpdate(
    data: LaunchesSendLaunchUpdateData,
  ): CancelablePromise<LaunchesSendLaunchUpdateResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/launches/{launch_id}/send-update",
      path: {
        launch_id: data.launchId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class LocationsService {
  /**
   * Read Locations
   * Retrieve locations.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns LocationsPublic Successful Response
   * @throws ApiError
   */
  public static readLocations(
    data: LocationsReadLocationsData = {},
  ): CancelablePromise<LocationsReadLocationsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/locations/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Location
   * Create new location.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns LocationPublic Successful Response
   * @throws ApiError
   */
  public static createLocation(
    data: LocationsCreateLocationData,
  ): CancelablePromise<LocationsCreateLocationResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/locations/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Location
   * Get location by ID.
   * @param data The data for the request.
   * @param data.locationId
   * @returns LocationPublic Successful Response
   * @throws ApiError
   */
  public static readLocation(
    data: LocationsReadLocationData,
  ): CancelablePromise<LocationsReadLocationResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/locations/{location_id}",
      path: {
        location_id: data.locationId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Location
   * Update a location.
   * @param data The data for the request.
   * @param data.locationId
   * @param data.requestBody
   * @returns LocationPublic Successful Response
   * @throws ApiError
   */
  public static updateLocation(
    data: LocationsUpdateLocationData,
  ): CancelablePromise<LocationsUpdateLocationResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/locations/{location_id}",
      path: {
        location_id: data.locationId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Location
   * Delete a location.
   * @param data The data for the request.
   * @param data.locationId
   * @returns void Successful Response
   * @throws ApiError
   */
  public static deleteLocation(
    data: LocationsDeleteLocationData,
  ): CancelablePromise<LocationsDeleteLocationResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/locations/{location_id}",
      path: {
        location_id: data.locationId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class LoginService {
  /**
   * Login Access Token
   * OAuth2 compatible token login, get an access token for future requests
   * @param data The data for the request.
   * @param data.formData
   * @returns Token Successful Response
   * @throws ApiError
   */
  public static loginAccessToken(
    data: LoginLoginAccessTokenData,
  ): CancelablePromise<LoginLoginAccessTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/login/access-token",
      formData: data.formData,
      mediaType: "application/x-www-form-urlencoded",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Test Token
   * Test access token
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static testToken(): CancelablePromise<LoginTestTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/login/test-token",
    })
  }

  /**
   * Recover Password
   * Password Recovery
   * @param data The data for the request.
   * @param data.email
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static recoverPassword(
    data: LoginRecoverPasswordData,
  ): CancelablePromise<LoginRecoverPasswordResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/password-recovery/{email}",
      path: {
        email: data.email,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Reset Password
   * Reset password
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static resetPassword(
    data: LoginResetPasswordData,
  ): CancelablePromise<LoginResetPasswordResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/reset-password/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Recover Password Html Content
   * HTML Content for Password Recovery
   * @param data The data for the request.
   * @param data.email
   * @returns string Successful Response
   * @throws ApiError
   */
  public static recoverPasswordHtmlContent(
    data: LoginRecoverPasswordHtmlContentData,
  ): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/password-recovery-html-content/{email}",
      path: {
        email: data.email,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class MerchandiseService {
  /**
   * Read Merchandise List
   * Retrieve merchandise (catalog) with pagination.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns MerchandisesPublic Successful Response
   * @throws ApiError
   */
  public static readMerchandiseList(
    data: MerchandiseReadMerchandiseListData = {},
  ): CancelablePromise<MerchandiseReadMerchandiseListResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/merchandise/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Merchandise
   * Create new merchandise (catalog item).
   * @param data The data for the request.
   * @param data.requestBody
   * @returns MerchandisePublic Successful Response
   * @throws ApiError
   */
  public static createMerchandise(
    data: MerchandiseCreateMerchandiseData,
  ): CancelablePromise<MerchandiseCreateMerchandiseResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/merchandise/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Merchandise
   * Get merchandise by ID.
   * @param data The data for the request.
   * @param data.merchandiseId
   * @returns MerchandisePublic Successful Response
   * @throws ApiError
   */
  public static readMerchandise(
    data: MerchandiseReadMerchandiseData,
  ): CancelablePromise<MerchandiseReadMerchandiseResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/merchandise/{merchandise_id}",
      path: {
        merchandise_id: data.merchandiseId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Merchandise
   * Update merchandise.
   * @param data The data for the request.
   * @param data.merchandiseId
   * @param data.requestBody
   * @returns MerchandisePublic Successful Response
   * @throws ApiError
   */
  public static updateMerchandise(
    data: MerchandiseUpdateMerchandiseData,
  ): CancelablePromise<MerchandiseUpdateMerchandiseResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/merchandise/{merchandise_id}",
      path: {
        merchandise_id: data.merchandiseId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Merchandise
   * Delete merchandise. Fails if still offered on any trip.
   * @param data The data for the request.
   * @param data.merchandiseId
   * @returns void Successful Response
   * @throws ApiError
   */
  public static deleteMerchandise(
    data: MerchandiseDeleteMerchandiseData,
  ): CancelablePromise<MerchandiseDeleteMerchandiseResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/merchandise/{merchandise_id}",
      path: {
        merchandise_id: data.merchandiseId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class MissionsService {
  /**
   * Read Missions
   * Retrieve missions with booking statistics.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns MissionsWithStatsPublic Successful Response
   * @throws ApiError
   */
  public static readMissions(
    data: MissionsReadMissionsData = {},
  ): CancelablePromise<MissionsReadMissionsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/missions/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Mission
   * Create new mission.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns MissionPublic Successful Response
   * @throws ApiError
   */
  public static createMission(
    data: MissionsCreateMissionData,
  ): CancelablePromise<MissionsCreateMissionResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/missions/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Mission
   * Get mission by ID.
   * @param data The data for the request.
   * @param data.missionId
   * @returns MissionPublic Successful Response
   * @throws ApiError
   */
  public static readMission(
    data: MissionsReadMissionData,
  ): CancelablePromise<MissionsReadMissionResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/missions/{mission_id}",
      path: {
        mission_id: data.missionId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Mission
   * Update a mission.
   * @param data The data for the request.
   * @param data.missionId
   * @param data.requestBody
   * @param data.allowPastEdit
   * @returns MissionPublic Successful Response
   * @throws ApiError
   */
  public static updateMission(
    data: MissionsUpdateMissionData,
  ): CancelablePromise<MissionsUpdateMissionResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/missions/{mission_id}",
      path: {
        mission_id: data.missionId,
      },
      query: {
        allow_past_edit: data.allowPastEdit,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Mission
   * Delete a mission.
   * @param data The data for the request.
   * @param data.missionId
   * @returns void Successful Response
   * @throws ApiError
   */
  public static deleteMission(
    data: MissionsDeleteMissionData,
  ): CancelablePromise<MissionsDeleteMissionResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/missions/{mission_id}",
      path: {
        mission_id: data.missionId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Missions By Launch
   * Retrieve missions for a specific launch.
   * @param data The data for the request.
   * @param data.launchId
   * @param data.skip
   * @param data.limit
   * @returns MissionsPublic Successful Response
   * @throws ApiError
   */
  public static readMissionsByLaunch(
    data: MissionsReadMissionsByLaunchData,
  ): CancelablePromise<MissionsReadMissionsByLaunchResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/missions/launch/{launch_id}",
      path: {
        launch_id: data.launchId,
      },
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Active Missions
   * Retrieve active missions.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns MissionsPublic Successful Response
   * @throws ApiError
   */
  public static readActiveMissions(
    data: MissionsReadActiveMissionsData = {},
  ): CancelablePromise<MissionsReadActiveMissionsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/missions/active/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Public Missions
   * Retrieve public missions.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns MissionsPublic Successful Response
   * @throws ApiError
   */
  public static readPublicMissions(
    data: MissionsReadPublicMissionsData = {},
  ): CancelablePromise<MissionsReadPublicMissionsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/missions/public/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Import Mission From Yaml
   * Import a mission from YAML file.
   *
   * Expected YAML format:
   * ```yaml
   * name: "Mars Sample Return"
   * description: "Return samples from Mars to Earth"
   * launch_id: "spacex-falcon-heavy-2024-03-15"
   * duration_days: 1095
   * status: "planned"
   * ```
   * @param data The data for the request.
   * @param data.formData
   * @returns MissionPublic Successful Response
   * @throws ApiError
   */
  public static importMissionFromYaml(
    data: MissionsImportMissionFromYamlData,
  ): CancelablePromise<MissionsImportMissionFromYamlResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/missions/import-yaml",
      formData: data.formData,
      mediaType: "multipart/form-data",
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class PaymentsService {
  /**
   * Create Payment Intent Endpoint
   * Create a Stripe PaymentIntent for the specified amount.
   *
   * Args:
   * amount: Amount in cents (e.g., 1000 for $10.00)
   * currency: Currency code (default: "usd")
   *
   * Returns:
   * dict: Payment intent client secret and ID
   * @param data The data for the request.
   * @param data.amount
   * @param data.currency
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static createPaymentIntentEndpoint(
    data: PaymentsCreatePaymentIntentEndpointData,
  ): CancelablePromise<PaymentsCreatePaymentIntentEndpointResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/payments/create-payment-intent",
      query: {
        amount: data.amount,
        currency: data.currency,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Verify Payment
   * Verify a payment intent's status.
   *
   * Args:
   * payment_intent_id: The ID of the payment intent to verify
   *
   * Returns:
   * dict: Payment status information
   * @param data The data for the request.
   * @param data.paymentIntentId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static verifyPayment(
    data: PaymentsVerifyPaymentData,
  ): CancelablePromise<PaymentsVerifyPaymentResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/payments/verify-payment/{payment_intent_id}",
      path: {
        payment_intent_id: data.paymentIntentId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Stripe Webhook
   * Handle Stripe webhook events.
   *
   * Args:
   * request: The incoming webhook request
   *
   * Returns:
   * dict: Status of the webhook processing
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static stripeWebhook(): CancelablePromise<PaymentsStripeWebhookResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/payments/webhook",
    })
  }
}

export class PrivateService {
  /**
   * Create User
   * Create a new user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static createUser(
    data: PrivateCreateUserData,
  ): CancelablePromise<PrivateCreateUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/private/users/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class ProvidersService {
  /**
   * Read Public Providers
   * Retrieve providers with optional filtering by jurisdiction (public endpoint).
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @param data.jurisdictionId
   * @returns ProvidersPublic Successful Response
   * @throws ApiError
   */
  public static readPublicProviders(
    data: ProvidersReadPublicProvidersData = {},
  ): CancelablePromise<ProvidersReadPublicProvidersResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/providers/public/",
      query: {
        skip: data.skip,
        limit: data.limit,
        jurisdiction_id: data.jurisdictionId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Providers
   * Retrieve providers with optional filtering by jurisdiction.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @param data.jurisdictionId
   * @returns ProvidersPublic Successful Response
   * @throws ApiError
   */
  public static readProviders(
    data: ProvidersReadProvidersData = {},
  ): CancelablePromise<ProvidersReadProvidersResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/providers/",
      query: {
        skip: data.skip,
        limit: data.limit,
        jurisdiction_id: data.jurisdictionId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Provider
   * Create new provider.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns ProviderPublic Successful Response
   * @throws ApiError
   */
  public static createProvider(
    data: ProvidersCreateProviderData,
  ): CancelablePromise<ProvidersCreateProviderResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/providers/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Provider
   * Get provider by ID.
   * @param data The data for the request.
   * @param data.providerId
   * @returns ProviderPublic Successful Response
   * @throws ApiError
   */
  public static readProvider(
    data: ProvidersReadProviderData,
  ): CancelablePromise<ProvidersReadProviderResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/providers/{provider_id}",
      path: {
        provider_id: data.providerId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Provider
   * Update a provider.
   * @param data The data for the request.
   * @param data.providerId
   * @param data.requestBody
   * @returns ProviderPublic Successful Response
   * @throws ApiError
   */
  public static updateProvider(
    data: ProvidersUpdateProviderData,
  ): CancelablePromise<ProvidersUpdateProviderResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/providers/{provider_id}",
      path: {
        provider_id: data.providerId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Provider
   * Delete a provider.
   * @param data The data for the request.
   * @param data.providerId
   * @returns void Successful Response
   * @throws ApiError
   */
  public static deleteProvider(
    data: ProvidersDeleteProviderData,
  ): CancelablePromise<ProvidersDeleteProviderResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/providers/{provider_id}",
      path: {
        provider_id: data.providerId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Providers By Jurisdiction
   * Retrieve providers for a specific jurisdiction.
   * @param data The data for the request.
   * @param data.jurisdictionId
   * @param data.skip
   * @param data.limit
   * @returns ProvidersPublic Successful Response
   * @throws ApiError
   */
  public static readProvidersByJurisdiction(
    data: ProvidersReadProvidersByJurisdictionData,
  ): CancelablePromise<ProvidersReadProvidersByJurisdictionResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/providers/jurisdiction/{jurisdiction_id}",
      path: {
        jurisdiction_id: data.jurisdictionId,
      },
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Public Provider
   * Get provider by ID for public access.
   * No authentication required.
   * @param data The data for the request.
   * @param data.providerId
   * @returns ProviderPublic Successful Response
   * @throws ApiError
   */
  public static readPublicProvider(
    data: ProvidersReadPublicProviderData,
  ): CancelablePromise<ProvidersReadPublicProviderResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/providers/public/{provider_id}",
      path: {
        provider_id: data.providerId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class TripBoatsService {
  /**
   * Create Trip Boat
   * Create new trip boat association.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static createTripBoat(
    data: TripBoatsCreateTripBoatData,
  ): CancelablePromise<TripBoatsCreateTripBoatResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/trip-boats/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Trip Boats By Trip
   * Get all boats for a specific trip.
   * @param data The data for the request.
   * @param data.tripId
   * @param data.skip
   * @param data.limit
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static readTripBoatsByTrip(
    data: TripBoatsReadTripBoatsByTripData,
  ): CancelablePromise<TripBoatsReadTripBoatsByTripResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/trip-boats/trip/{trip_id}",
      path: {
        trip_id: data.tripId,
      },
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Trip Boats By Boat
   * Get all trips for a specific boat.
   * @param data The data for the request.
   * @param data.boatId
   * @param data.skip
   * @param data.limit
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static readTripBoatsByBoat(
    data: TripBoatsReadTripBoatsByBoatData,
  ): CancelablePromise<TripBoatsReadTripBoatsByBoatResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/trip-boats/boat/{boat_id}",
      path: {
        boat_id: data.boatId,
      },
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Trip Boat
   * Update a trip boat association.
   * @param data The data for the request.
   * @param data.tripBoatId
   * @param data.requestBody
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static updateTripBoat(
    data: TripBoatsUpdateTripBoatData,
  ): CancelablePromise<TripBoatsUpdateTripBoatResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/trip-boats/{trip_boat_id}",
      path: {
        trip_boat_id: data.tripBoatId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Trip Boat
   * Delete a trip boat association.
   * @param data The data for the request.
   * @param data.tripBoatId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static deleteTripBoat(
    data: TripBoatsDeleteTripBoatData,
  ): CancelablePromise<TripBoatsDeleteTripBoatResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/trip-boats/{trip_boat_id}",
      path: {
        trip_boat_id: data.tripBoatId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Public Trip Boats By Trip
   * Get all boats for a specific trip (public endpoint for booking form).
   * Validates that the trip's mission has public or early_bird booking_mode.
   * @param data The data for the request.
   * @param data.tripId
   * @param data.skip
   * @param data.limit
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static readPublicTripBoatsByTrip(
    data: TripBoatsReadPublicTripBoatsByTripData,
  ): CancelablePromise<TripBoatsReadPublicTripBoatsByTripResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/trip-boats/public/trip/{trip_id}",
      path: {
        trip_id: data.tripId,
      },
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class TripMerchandiseService {
  /**
   * Create Trip Merchandise
   * Create new trip merchandise (link trip to catalog merchandise with optional overrides).
   * @param data The data for the request.
   * @param data.requestBody
   * @returns TripMerchandisePublic Successful Response
   * @throws ApiError
   */
  public static createTripMerchandise(
    data: TripMerchandiseCreateTripMerchandiseData,
  ): CancelablePromise<TripMerchandiseCreateTripMerchandiseResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/trip-merchandise/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * List Trip Merchandise
   * List trip merchandise with optional filtering by trip_id. Returns effective name, price, quantity.
   * @param data The data for the request.
   * @param data.tripId
   * @returns TripMerchandisePublic Successful Response
   * @throws ApiError
   */
  public static listTripMerchandise(
    data: TripMerchandiseListTripMerchandiseData = {},
  ): CancelablePromise<TripMerchandiseListTripMerchandiseResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/trip-merchandise/",
      query: {
        trip_id: data.tripId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Trip Merchandise
   * Get trip merchandise by ID.
   * @param data The data for the request.
   * @param data.tripMerchandiseId
   * @returns TripMerchandisePublic Successful Response
   * @throws ApiError
   */
  public static getTripMerchandise(
    data: TripMerchandiseGetTripMerchandiseData,
  ): CancelablePromise<TripMerchandiseGetTripMerchandiseResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/trip-merchandise/{trip_merchandise_id}",
      path: {
        trip_merchandise_id: data.tripMerchandiseId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Trip Merchandise
   * Update trip merchandise (quantity_available_override, price_override).
   * @param data The data for the request.
   * @param data.tripMerchandiseId
   * @param data.requestBody
   * @returns TripMerchandisePublic Successful Response
   * @throws ApiError
   */
  public static updateTripMerchandise(
    data: TripMerchandiseUpdateTripMerchandiseData,
  ): CancelablePromise<TripMerchandiseUpdateTripMerchandiseResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/trip-merchandise/{trip_merchandise_id}",
      path: {
        trip_merchandise_id: data.tripMerchandiseId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Trip Merchandise
   * Delete trip merchandise (unlink trip from catalog item).
   * @param data The data for the request.
   * @param data.tripMerchandiseId
   * @returns void Successful Response
   * @throws ApiError
   */
  public static deleteTripMerchandise(
    data: TripMerchandiseDeleteTripMerchandiseData,
  ): CancelablePromise<TripMerchandiseDeleteTripMerchandiseResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/trip-merchandise/{trip_merchandise_id}",
      path: {
        trip_merchandise_id: data.tripMerchandiseId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * List Public Trip Merchandise
   * List trip merchandise for a specific trip (public endpoint for booking form).
   * @param data The data for the request.
   * @param data.tripId
   * @returns TripMerchandisePublic Successful Response
   * @throws ApiError
   */
  public static listPublicTripMerchandise(
    data: TripMerchandiseListPublicTripMerchandiseData,
  ): CancelablePromise<TripMerchandiseListPublicTripMerchandiseResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/trip-merchandise/public/",
      query: {
        trip_id: data.tripId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class TripPricingService {
  /**
   * Create Trip Pricing
   * Create new trip pricing.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns TripPricingPublic Successful Response
   * @throws ApiError
   */
  public static createTripPricing(
    data: TripPricingCreateTripPricingData,
  ): CancelablePromise<TripPricingCreateTripPricingResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/trip-pricing/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * List Trip Pricing
   * List trip pricing with optional filtering.
   * @param data The data for the request.
   * @param data.tripId
   * @param data.ticketType
   * @returns TripPricingPublic Successful Response
   * @throws ApiError
   */
  public static listTripPricing(
    data: TripPricingListTripPricingData = {},
  ): CancelablePromise<TripPricingListTripPricingResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/trip-pricing/",
      query: {
        trip_id: data.tripId,
        ticket_type: data.ticketType,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Trip Pricing
   * Get trip pricing by ID.
   * @param data The data for the request.
   * @param data.tripPricingId
   * @returns TripPricingPublic Successful Response
   * @throws ApiError
   */
  public static getTripPricing(
    data: TripPricingGetTripPricingData,
  ): CancelablePromise<TripPricingGetTripPricingResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/trip-pricing/{trip_pricing_id}",
      path: {
        trip_pricing_id: data.tripPricingId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Trip Pricing
   * Update trip pricing.
   * @param data The data for the request.
   * @param data.tripPricingId
   * @param data.requestBody
   * @returns TripPricingPublic Successful Response
   * @throws ApiError
   */
  public static updateTripPricing(
    data: TripPricingUpdateTripPricingData,
  ): CancelablePromise<TripPricingUpdateTripPricingResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/trip-pricing/{trip_pricing_id}",
      path: {
        trip_pricing_id: data.tripPricingId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Trip Pricing
   * Delete trip pricing.
   * @param data The data for the request.
   * @param data.tripPricingId
   * @returns void Successful Response
   * @throws ApiError
   */
  public static deleteTripPricing(
    data: TripPricingDeleteTripPricingData,
  ): CancelablePromise<TripPricingDeleteTripPricingResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/trip-pricing/{trip_pricing_id}",
      path: {
        trip_pricing_id: data.tripPricingId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * List Public Trip Pricing
   * List trip pricing for a specific trip (public endpoint for booking form).
   * Validates that the trip's mission has public or early_bird booking_mode.
   * @param data The data for the request.
   * @param data.tripId
   * @returns TripPricingPublic Successful Response
   * @throws ApiError
   */
  public static listPublicTripPricing(
    data: TripPricingListPublicTripPricingData,
  ): CancelablePromise<TripPricingListPublicTripPricingResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/trip-pricing/public/",
      query: {
        trip_id: data.tripId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class TripsService {
  /**
   * Read Trips
   * Retrieve trips.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns TripsPublic Successful Response
   * @throws ApiError
   */
  public static readTrips(
    data: TripsReadTripsData = {},
  ): CancelablePromise<TripsReadTripsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/trips/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Trip
   * Create new trip.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns TripPublic Successful Response
   * @throws ApiError
   */
  public static createTrip(
    data: TripsCreateTripData,
  ): CancelablePromise<TripsCreateTripResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/trips/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Trip
   * Get trip by ID.
   * @param data The data for the request.
   * @param data.tripId
   * @returns TripPublic Successful Response
   * @throws ApiError
   */
  public static readTrip(
    data: TripsReadTripData,
  ): CancelablePromise<TripsReadTripResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/trips/{trip_id}",
      path: {
        trip_id: data.tripId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Trip
   * Update a trip.
   * @param data The data for the request.
   * @param data.tripId
   * @param data.requestBody
   * @param data.allowPastEdit
   * @returns TripPublic Successful Response
   * @throws ApiError
   */
  public static updateTrip(
    data: TripsUpdateTripData,
  ): CancelablePromise<TripsUpdateTripResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/trips/{trip_id}",
      path: {
        trip_id: data.tripId,
      },
      query: {
        allow_past_edit: data.allowPastEdit,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Trip
   * Delete a trip.
   * @param data The data for the request.
   * @param data.tripId
   * @returns TripPublic Successful Response
   * @throws ApiError
   */
  public static deleteTrip(
    data: TripsDeleteTripData,
  ): CancelablePromise<TripsDeleteTripResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/trips/{trip_id}",
      path: {
        trip_id: data.tripId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Trips By Mission
   * Retrieve trips for a specific mission.
   * @param data The data for the request.
   * @param data.missionId
   * @param data.skip
   * @param data.limit
   * @returns TripsPublic Successful Response
   * @throws ApiError
   */
  public static readTripsByMission(
    data: TripsReadTripsByMissionData,
  ): CancelablePromise<TripsReadTripsByMissionResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/trips/mission/{mission_id}",
      path: {
        mission_id: data.missionId,
      },
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Public Trips
   * Retrieve public trips for booking form.
   * Filters by booking_mode:
   * - private: Not shown unless admin
   * - early_bird: Shown if valid access_code provided
   * - public: Always shown
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @param data.accessCode
   * @returns TripsPublic Successful Response
   * @throws ApiError
   */
  public static readPublicTrips(
    data: TripsReadPublicTripsData = {},
  ): CancelablePromise<TripsReadPublicTripsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/trips/public/",
      query: {
        skip: data.skip,
        limit: data.limit,
        access_code: data.accessCode,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Public Trip
   * Get public trip by ID for booking form.
   * Checks booking_mode to determine access.
   * @param data The data for the request.
   * @param data.tripId
   * @param data.accessCode
   * @returns TripPublic Successful Response
   * @throws ApiError
   */
  public static readPublicTrip(
    data: TripsReadPublicTripData,
  ): CancelablePromise<TripsReadPublicTripResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/trips/public/{trip_id}",
      path: {
        trip_id: data.tripId,
      },
      query: {
        access_code: data.accessCode,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Import Trip From Yaml
   * Import a trip from YAML file.
   *
   * Expected YAML format:
   * ```yaml
   * name: "Mars Sample Return Viewing Experience"
   * mission_id: "mars-sample-return"
   * type: "launch_viewing"
   * base_price: 299.99
   * departure_time: "2024-03-15T10:00:00Z"
   * return_time: "2024-03-15T18:00:00Z"
   * departure_location_id: "port-canaveral-marina"
   * description: "Watch the historic Mars Sample Return launch"
   * max_capacity: 50
   * ```
   * @param data The data for the request.
   * @param data.formData
   * @returns TripPublic Successful Response
   * @throws ApiError
   */
  public static importTripFromYaml(
    data: TripsImportTripFromYamlData,
  ): CancelablePromise<TripsImportTripFromYamlResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/trips/import-yaml",
      formData: data.formData,
      mediaType: "multipart/form-data",
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class UsersService {
  /**
   * Read Users
   * Retrieve users.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns UsersPublic Successful Response
   * @throws ApiError
   */
  public static readUsers(
    data: UsersReadUsersData = {},
  ): CancelablePromise<UsersReadUsersResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create User
   * Create new user (superuser only - all users must be superusers).
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static createUser(
    data: UsersCreateUserData,
  ): CancelablePromise<UsersCreateUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read User Me
   * Get current user (superuser only).
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/me",
    })
  }

  /**
   * Delete User Me
   * Delete own user (superuser only, but not allowed).
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/users/me",
    })
  }

  /**
   * Update User Me
   * Update own user (superuser only).
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static updateUserMe(
    data: UsersUpdateUserMeData,
  ): CancelablePromise<UsersUpdateUserMeResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/me",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Password Me
   * Update own password (superuser only).
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static updatePasswordMe(
    data: UsersUpdatePasswordMeData,
  ): CancelablePromise<UsersUpdatePasswordMeResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/me/password",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read User By Id
   * Get a specific user by id (superuser only).
   * @param data The data for the request.
   * @param data.userId
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static readUserById(
    data: UsersReadUserByIdData,
  ): CancelablePromise<UsersReadUserByIdResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update User
   * Update a user.
   * @param data The data for the request.
   * @param data.userId
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static updateUser(
    data: UsersUpdateUserData,
  ): CancelablePromise<UsersUpdateUserResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete User
   * Delete a user (superuser only).
   * @param data The data for the request.
   * @param data.userId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteUser(
    data: UsersDeleteUserData,
  ): CancelablePromise<UsersDeleteUserResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class UtilsService {
  /**
   * Test Email
   * Test emails.
   * @param data The data for the request.
   * @param data.emailTo
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static testEmail(
    data: UtilsTestEmailData,
  ): CancelablePromise<UtilsTestEmailResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/utils/test-email/",
      query: {
        email_to: data.emailTo,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Health Check
   * Health check endpoint.
   * @returns string Successful Response
   * @throws ApiError
   */
  public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/utils/health-check/",
    })
  }

  /**
   * Get Us States
   * Get a list of US states.
   * @returns string Successful Response
   * @throws ApiError
   */
  public static getUsStates(): CancelablePromise<UtilsGetUsStatesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/utils/us-states/",
    })
  }
}
