// This file is auto-generated by @hey-api/openapi-ts

/**
 * Response model for access code validation.
 */
export type AccessCodeValidationResponse = {
  valid: boolean
  message?: string | null
  discount_code?: DiscountCodePublic | null
}

export type BoatCreate = {
  name: string
  slug?: string
  capacity: number
  provider_name?: string | null
  provider_location?: string | null
  provider_address?: string | null
  jurisdiction_id: string
  map_link?: string | null
}

export type BoatPublic = {
  name: string
  slug?: string
  capacity: number
  provider_name?: string | null
  provider_location?: string | null
  provider_address?: string | null
  jurisdiction_id: string
  map_link?: string | null
  id: string
  created_at: string
  updated_at: string
}

export type BoatsPublic = {
  data: Array<BoatPublic>
  count: number
}

export type BoatUpdate = {
  name?: string | null
  capacity?: number | null
  provider_name?: string | null
  provider_location?: string | null
  provider_address?: string | null
  jurisdiction_id?: string | null
  map_link?: string | null
}

export type Body_launches_import_launch_from_yaml = {
  file: Blob | File
}

export type Body_login_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

export type Body_missions_import_mission_from_yaml = {
  file: Blob | File
}

export type Body_trips_import_trip_from_yaml = {
  file: Blob | File
}

export type BookingCreate = {
  confirmation_code: string
  user_name: string
  user_email: string
  user_phone: string
  billing_address: string
  subtotal: number
  discount_amount: number
  tax_amount: number
  tip_amount: number
  total_amount: number
  special_requests?: string | null
  launch_updates_pref?: boolean
  discount_code_id?: string | null
  items: Array<BookingItemCreate>
}

export type BookingItemCreate = {
  trip_id: string
  boat_id: string
  trip_merchandise_id?: string | null
  item_type: string
  quantity: number
  price_per_unit: number
  status?: BookingItemStatus
  refund_reason?: string | null
  refund_notes?: string | null
}

export type BookingItemPublic = {
  booking_id: string
  trip_id: string
  boat_id: string
  trip_merchandise_id?: string | null
  item_type: string
  quantity: number
  price_per_unit: number
  status?: BookingItemStatus
  refund_reason?: string | null
  refund_notes?: string | null
  id: string
  created_at: string
  updated_at: string
}

export type BookingItemStatus = "active" | "refunded" | "fulfilled"

export type BookingPublic = {
  confirmation_code: string
  user_name: string
  user_email: string
  user_phone: string
  billing_address: string
  subtotal: number
  discount_amount: number
  tax_amount: number
  tip_amount: number
  total_amount: number
  payment_intent_id?: string | null
  special_requests?: string | null
  status?: BookingStatus
  launch_updates_pref?: boolean
  discount_code_id?: string | null
  id: string
  created_at: string
  updated_at: string
  items: Array<BookingItemPublic>
  qr_code_base64?: string | null
  mission_id?: string | null
  mission_name?: string | null
  discount_code?: DiscountCodePublic | null
}

export type BookingsPaginatedResponse = {
  data: Array<BookingPublic>
  total: number
  page: number
  per_page: number
  total_pages: number
}

export type BookingStatus =
  | "draft"
  | "pending_payment"
  | "confirmed"
  | "checked_in"
  | "completed"
  | "cancelled"
  | "refunded"

export type BookingUpdate = {
  status?: BookingStatus | null
  special_requests?: string | null
  tip_amount?: number | null
  discount_amount?: number | null
  tax_amount?: number | null
  total_amount?: number | null
  launch_updates_pref?: boolean | null
  discount_code_id?: string | null
}

export type DiscountCodeCreate = {
  code: string
  description?: string | null
  discount_type: DiscountCodeType
  discount_value: number
  max_uses?: number | null
  is_active?: boolean
  valid_from?: string | null
  valid_until?: string | null
  min_order_amount?: number | null
  max_discount_amount?: number | null
  is_access_code?: boolean
  access_code_mission_id?: string | null
}

export type DiscountCodePublic = {
  code: string
  description?: string | null
  discount_type: DiscountCodeType
  discount_value: number
  max_uses?: number | null
  used_count?: number
  is_active?: boolean
  valid_from?: string | null
  valid_until?: string | null
  min_order_amount?: number | null
  max_discount_amount?: number | null
  is_access_code?: boolean
  access_code_mission_id?: string | null
  id: string
  created_at: string
  updated_at: string
}

export type DiscountCodeType = "percentage" | "fixed_amount"

export type DiscountCodeUpdate = {
  code?: string | null
  description?: string | null
  discount_type?: DiscountCodeType | null
  discount_value?: number | null
  max_uses?: number | null
  is_active?: boolean | null
  valid_from?: string | null
  valid_until?: string | null
  min_order_amount?: number | null
  max_discount_amount?: number | null
  is_access_code?: boolean | null
  access_code_mission_id?: string | null
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type ItemCreate = {
  title: string
  description?: string | null
}

export type ItemPublic = {
  title: string
  description?: string | null
  id: string
  owner_id: string
}

export type ItemsPublic = {
  data: Array<ItemPublic>
  count: number
}

export type ItemUpdate = {
  title?: string | null
  description?: string | null
}

export type JurisdictionCreate = {
  name: string
  state: string
  sales_tax_rate: number
  location_id: string
}

export type JurisdictionPublic = {
  name: string
  state: string
  sales_tax_rate: number
  location_id: string
  id: string
  created_at: string
  updated_at: string
}

export type JurisdictionsPublic = {
  data: Array<JurisdictionPublic>
  count: number
}

export type JurisdictionUpdate = {
  name?: string | null
  state?: string | null
  sales_tax_rate?: number | null
  location_id?: string | null
}

export type LaunchCreate = {
  name: string
  launch_timestamp: string
  summary: string
  location_id: string
}

export type LaunchesPublic = {
  data: Array<LaunchPublic>
  count: number
}

export type LaunchPublic = {
  name: string
  launch_timestamp: string
  summary: string
  location_id: string
  id: string
  created_at: string
  updated_at: string
}

export type LaunchUpdate = {
  name?: string | null
  launch_timestamp?: string | null
  summary?: string | null
  location_id?: string | null
}

/**
 * Request body for sending launch update emails.
 */
export type LaunchUpdateMessage = {
  message: string
}

/**
 * Response for launch update email sending.
 */
export type LaunchUpdateResponse = {
  emails_sent: number
  emails_failed: number
  recipients: Array<string>
}

export type LocationCreate = {
  name: string
  state: string
}

export type LocationPublic = {
  name: string
  state: string
  id: string
  created_at: string
  updated_at: string
}

export type LocationsPublic = {
  data: Array<LocationPublic>
  count: number
}

export type LocationUpdate = {
  name?: string | null
  state?: string | null
}

export type Message = {
  message: string
}

export type MissionCreate = {
  name: string
  launch_id: string
  active?: boolean
  public?: boolean
  booking_mode?: string
  sales_open_at?: string | null
  refund_cutoff_hours?: number
}

export type MissionPublic = {
  name: string
  launch_id: string
  active?: boolean
  public?: boolean
  booking_mode?: string
  sales_open_at?: string | null
  refund_cutoff_hours?: number
  id: string
  created_at: string
  updated_at: string
}

export type MissionsPublic = {
  data: Array<MissionPublic>
  count: number
}

export type MissionsWithStatsPublic = {
  data: Array<MissionWithStats>
  count: number
}

export type MissionUpdate = {
  name?: string | null
  launch_id?: string | null
  active?: boolean | null
  public?: boolean | null
  booking_mode?: string | null
  sales_open_at?: string | null
  refund_cutoff_hours?: number | null
}

export type MissionWithStats = {
  name: string
  launch_id: string
  active?: boolean
  public?: boolean
  booking_mode?: string
  sales_open_at?: string | null
  refund_cutoff_hours?: number
  id: string
  created_at: string
  updated_at: string
  total_bookings?: number
  total_sales?: number
}

export type NewPassword = {
  token: string
  new_password: string
}

export type PrivateUserCreate = {
  email: string
  password: string
  full_name: string
  is_verified?: boolean
}

export type Token = {
  access_token: string
  token_type?: string
}

export type TripBoatCreate = {
  trip_id: string
  boat_id: string
  max_capacity?: number | null
}

export type TripBoatPublic = {
  trip_id: string
  boat_id: string
  max_capacity?: number | null
  id: string
  created_at: string
  updated_at: string
  boat: BoatPublic
}

export type TripBoatUpdate = {
  trip_id?: string | null
  boat_id?: string | null
  max_capacity?: number | null
}

export type TripCreate = {
  mission_id: string
  type: string
  active?: boolean
  check_in_time: string
  boarding_time: string
  departure_time: string
}

export type TripMerchandiseCreate = {
  trip_id: string
  name: string
  description?: string | null
  price: number
  quantity_available: number
}

export type TripMerchandisePublic = {
  trip_id: string
  name: string
  description?: string | null
  price: number
  quantity_available: number
  id: string
  created_at: string
  updated_at: string
}

export type TripMerchandiseUpdate = {
  name?: string | null
  description?: string | null
  price?: number | null
  quantity_available?: number | null
}

export type TripPricingCreate = {
  trip_id: string
  ticket_type: string
  price: number
}

export type TripPricingPublic = {
  trip_id: string
  ticket_type: string
  price: number
  id: string
  created_at: string
  updated_at: string
}

export type TripPricingUpdate = {
  ticket_type?: string | null
  price?: number | null
}

export type TripPublic = {
  mission_id: string
  type: string
  active?: boolean
  check_in_time: string
  boarding_time: string
  departure_time: string
  id: string
  created_at: string
  updated_at: string
  trip_boats?: Array<TripBoatPublic>
}

export type TripsPublic = {
  data: Array<TripPublic>
  count: number
}

export type TripUpdate = {
  mission_id?: string | null
  type?: string | null
  active?: boolean | null
  check_in_time?: string | null
  boarding_time?: string | null
  departure_time?: string | null
}

export type UpdatePassword = {
  current_password: string
  new_password: string
}

export type UserCreate = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  password: string
}

export type UserPublic = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  id: string
}

export type UserRegister = {
  email: string
  password: string
  full_name?: string | null
}

export type UsersPublic = {
  data: Array<UserPublic>
  count: number
}

export type UserUpdate = {
  email?: string | null
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  password?: string | null
}

export type UserUpdateMe = {
  full_name?: string | null
  email?: string | null
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type BoatsReadBoatsData = {
  limit?: number
  skip?: number
}

export type BoatsReadBoatsResponse = BoatsPublic

export type BoatsCreateBoatData = {
  requestBody: BoatCreate
}

export type BoatsCreateBoatResponse = BoatPublic

export type BoatsReadBoatData = {
  boatId: string
}

export type BoatsReadBoatResponse = BoatPublic

export type BoatsUpdateBoatData = {
  boatId: string
  requestBody: BoatUpdate
}

export type BoatsUpdateBoatResponse = BoatPublic

export type BoatsDeleteBoatData = {
  boatId: string
}

export type BoatsDeleteBoatResponse = void

export type BoatsReadBoatsByJurisdictionData = {
  jurisdictionId: string
  limit?: number
  skip?: number
}

export type BoatsReadBoatsByJurisdictionResponse = BoatsPublic

export type BoatsReadPublicBoatData = {
  boatId: string
}

export type BoatsReadPublicBoatResponse = BoatPublic

export type BoatsReadPublicBoatsData = {
  limit?: number
  skip?: number
}

export type BoatsReadPublicBoatsResponse = BoatsPublic

export type BookingsCreateBookingData = {
  requestBody: BookingCreate
}

export type BookingsCreateBookingResponse = BookingPublic

export type BookingsListBookingsData = {
  limit?: number
  missionId?: string | null
  skip?: number
  sortBy?: string
  sortDirection?: string
}

export type BookingsListBookingsResponse = BookingsPaginatedResponse

export type BookingsGetBookingByIdData = {
  bookingId: string
}

export type BookingsGetBookingByIdResponse = BookingPublic

export type BookingsUpdateBookingData = {
  bookingId: string
  requestBody: BookingUpdate
}

export type BookingsUpdateBookingResponse = BookingPublic

export type BookingsCheckInBookingData = {
  boatId?: string | null
  confirmationCode: string
  tripId?: string | null
}

export type BookingsCheckInBookingResponse = BookingPublic

export type BookingsProcessRefundData = {
  confirmationCode: string
  refundAmount?: number | null
  refundNotes?: string | null
  refundReason: string
}

export type BookingsProcessRefundResponse = BookingPublic

export type BookingsExportBookingsCsvData = {
  bookingStatus?: string | null
  missionId?: string | null
  tripId?: string | null
}

export type BookingsExportBookingsCsvResponse = unknown

export type BookingsGetBookingQrCodeData = {
  confirmationCode: string
}

export type BookingsGetBookingQrCodeResponse = unknown

export type BookingsGetBookingByConfirmationCodeData = {
  confirmationCode: string
}

export type BookingsGetBookingByConfirmationCodeResponse = BookingPublic

export type BookingsResendBookingConfirmationEmailData = {
  confirmationCode: string
}

export type BookingsResendBookingConfirmationEmailResponse = {
  [key: string]: unknown
}

export type BookingsInitializePaymentData = {
  confirmationCode: string
}

export type BookingsInitializePaymentResponse = {
  [key: string]: unknown
}

export type DiscountCodesCreateDiscountCodeData = {
  requestBody: DiscountCodeCreate
}

export type DiscountCodesCreateDiscountCodeResponse = DiscountCodePublic

export type DiscountCodesListDiscountCodesData = {
  isActive?: boolean | null
  limit?: number
  skip?: number
}

export type DiscountCodesListDiscountCodesResponse = Array<DiscountCodePublic>

export type DiscountCodesGetDiscountCodeData = {
  discountCodeId: string
}

export type DiscountCodesGetDiscountCodeResponse = DiscountCodePublic

export type DiscountCodesUpdateDiscountCodeData = {
  discountCodeId: string
  requestBody: DiscountCodeUpdate
}

export type DiscountCodesUpdateDiscountCodeResponse = DiscountCodePublic

export type DiscountCodesDeleteDiscountCodeData = {
  discountCodeId: string
}

export type DiscountCodesDeleteDiscountCodeResponse = {
  [key: string]: string
}

export type DiscountCodesValidateDiscountCodeData = {
  code: string
  subtotal?: number
}

export type DiscountCodesValidateDiscountCodeResponse = DiscountCodePublic

export type DiscountCodesValidateAccessCodeData = {
  code: string
  missionId?: string | null
}

export type DiscountCodesValidateAccessCodeResponse =
  AccessCodeValidationResponse

export type ItemsReadItemsData = {
  limit?: number
  skip?: number
}

export type ItemsReadItemsResponse = ItemsPublic

export type ItemsCreateItemData = {
  requestBody: ItemCreate
}

export type ItemsCreateItemResponse = ItemPublic

export type ItemsReadItemData = {
  id: string
}

export type ItemsReadItemResponse = ItemPublic

export type ItemsUpdateItemData = {
  id: string
  requestBody: ItemUpdate
}

export type ItemsUpdateItemResponse = ItemPublic

export type ItemsDeleteItemData = {
  id: string
}

export type ItemsDeleteItemResponse = Message

export type JurisdictionsReadJurisdictionsData = {
  limit?: number
  locationId?: string
  skip?: number
}

export type JurisdictionsReadJurisdictionsResponse = JurisdictionsPublic

export type JurisdictionsCreateJurisdictionData = {
  requestBody: JurisdictionCreate
}

export type JurisdictionsCreateJurisdictionResponse = JurisdictionPublic

export type JurisdictionsReadJurisdictionData = {
  jurisdictionId: string
}

export type JurisdictionsReadJurisdictionResponse = JurisdictionPublic

export type JurisdictionsUpdateJurisdictionData = {
  jurisdictionId: string
  requestBody: JurisdictionUpdate
}

export type JurisdictionsUpdateJurisdictionResponse = JurisdictionPublic

export type JurisdictionsDeleteJurisdictionData = {
  jurisdictionId: string
}

export type JurisdictionsDeleteJurisdictionResponse = void

export type LaunchesReadLaunchesData = {
  limit?: number
  skip?: number
}

export type LaunchesReadLaunchesResponse = LaunchesPublic

export type LaunchesCreateLaunchData = {
  requestBody: LaunchCreate
}

export type LaunchesCreateLaunchResponse = LaunchPublic

export type LaunchesReadLaunchData = {
  launchId: string
}

export type LaunchesReadLaunchResponse = LaunchPublic

export type LaunchesUpdateLaunchData = {
  launchId: string
  requestBody: LaunchUpdate
}

export type LaunchesUpdateLaunchResponse = LaunchPublic

export type LaunchesDeleteLaunchData = {
  launchId: string
}

export type LaunchesDeleteLaunchResponse = void

export type LaunchesReadLaunchesByLocationData = {
  limit?: number
  locationId: string
  skip?: number
}

export type LaunchesReadLaunchesByLocationResponse = LaunchesPublic

export type LaunchesReadPublicLaunchesData = {
  limit?: number
  skip?: number
}

export type LaunchesReadPublicLaunchesResponse = LaunchesPublic

export type LaunchesReadPublicLaunchData = {
  launchId: string
}

export type LaunchesReadPublicLaunchResponse = LaunchPublic

export type LaunchesImportLaunchFromYamlData = {
  formData: Body_launches_import_launch_from_yaml
}

export type LaunchesImportLaunchFromYamlResponse = LaunchPublic

export type LaunchesSendLaunchUpdateData = {
  launchId: string
  requestBody: LaunchUpdateMessage
}

export type LaunchesSendLaunchUpdateResponse = LaunchUpdateResponse

export type LocationsReadLocationsData = {
  limit?: number
  skip?: number
}

export type LocationsReadLocationsResponse = LocationsPublic

export type LocationsCreateLocationData = {
  requestBody: LocationCreate
}

export type LocationsCreateLocationResponse = LocationPublic

export type LocationsReadLocationData = {
  locationId: string
}

export type LocationsReadLocationResponse = LocationPublic

export type LocationsUpdateLocationData = {
  locationId: string
  requestBody: LocationUpdate
}

export type LocationsUpdateLocationResponse = LocationPublic

export type LocationsDeleteLocationData = {
  locationId: string
}

export type LocationsDeleteLocationResponse = void

export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token
}

export type LoginLoginAccessTokenResponse = Token

export type LoginTestTokenResponse = UserPublic

export type LoginRecoverPasswordData = {
  email: string
}

export type LoginRecoverPasswordResponse = Message

export type LoginResetPasswordData = {
  requestBody: NewPassword
}

export type LoginResetPasswordResponse = Message

export type LoginRecoverPasswordHtmlContentData = {
  email: string
}

export type LoginRecoverPasswordHtmlContentResponse = string

export type MissionsReadMissionsData = {
  limit?: number
  skip?: number
}

export type MissionsReadMissionsResponse = MissionsWithStatsPublic

export type MissionsCreateMissionData = {
  requestBody: MissionCreate
}

export type MissionsCreateMissionResponse = MissionPublic

export type MissionsReadMissionData = {
  missionId: string
}

export type MissionsReadMissionResponse = MissionPublic

export type MissionsUpdateMissionData = {
  missionId: string
  requestBody: MissionUpdate
}

export type MissionsUpdateMissionResponse = MissionPublic

export type MissionsDeleteMissionData = {
  missionId: string
}

export type MissionsDeleteMissionResponse = void

export type MissionsReadMissionsByLaunchData = {
  launchId: string
  limit?: number
  skip?: number
}

export type MissionsReadMissionsByLaunchResponse = MissionsPublic

export type MissionsReadActiveMissionsData = {
  limit?: number
  skip?: number
}

export type MissionsReadActiveMissionsResponse = MissionsPublic

export type MissionsReadPublicMissionsData = {
  limit?: number
  skip?: number
}

export type MissionsReadPublicMissionsResponse = MissionsPublic

export type MissionsImportMissionFromYamlData = {
  formData: Body_missions_import_mission_from_yaml
}

export type MissionsImportMissionFromYamlResponse = MissionPublic

export type PaymentsCreatePaymentIntentEndpointData = {
  amount: number
  currency?: string
}

export type PaymentsCreatePaymentIntentEndpointResponse = {
  [key: string]: unknown
}

export type PaymentsVerifyPaymentData = {
  paymentIntentId: string
}

export type PaymentsVerifyPaymentResponse = {
  [key: string]: unknown
}

export type PaymentsStripeWebhookResponse = {
  [key: string]: unknown
}

export type PrivateCreateUserData = {
  requestBody: PrivateUserCreate
}

export type PrivateCreateUserResponse = UserPublic

export type TripBoatsCreateTripBoatData = {
  requestBody: TripBoatCreate
}

export type TripBoatsCreateTripBoatResponse = unknown

export type TripBoatsReadTripBoatsByTripData = {
  limit?: number
  skip?: number
  tripId: string
}

export type TripBoatsReadTripBoatsByTripResponse = unknown

export type TripBoatsReadTripBoatsByBoatData = {
  boatId: string
  limit?: number
  skip?: number
}

export type TripBoatsReadTripBoatsByBoatResponse = unknown

export type TripBoatsUpdateTripBoatData = {
  requestBody: TripBoatUpdate
  tripBoatId: string
}

export type TripBoatsUpdateTripBoatResponse = unknown

export type TripBoatsDeleteTripBoatData = {
  tripBoatId: string
}

export type TripBoatsDeleteTripBoatResponse = unknown

export type TripBoatsReadPublicTripBoatsByTripData = {
  limit?: number
  skip?: number
  tripId: string
}

export type TripBoatsReadPublicTripBoatsByTripResponse = unknown

export type TripMerchandiseCreateTripMerchandiseData = {
  requestBody: TripMerchandiseCreate
}

export type TripMerchandiseCreateTripMerchandiseResponse = TripMerchandisePublic

export type TripMerchandiseListTripMerchandiseData = {
  tripId?: string | null
}

export type TripMerchandiseListTripMerchandiseResponse =
  Array<TripMerchandisePublic>

export type TripMerchandiseGetTripMerchandiseData = {
  tripMerchandiseId: string
}

export type TripMerchandiseGetTripMerchandiseResponse = TripMerchandisePublic

export type TripMerchandiseUpdateTripMerchandiseData = {
  requestBody: TripMerchandiseUpdate
  tripMerchandiseId: string
}

export type TripMerchandiseUpdateTripMerchandiseResponse = TripMerchandisePublic

export type TripMerchandiseDeleteTripMerchandiseData = {
  tripMerchandiseId: string
}

export type TripMerchandiseDeleteTripMerchandiseResponse = void

export type TripMerchandiseListPublicTripMerchandiseData = {
  tripId: string
}

export type TripMerchandiseListPublicTripMerchandiseResponse =
  Array<TripMerchandisePublic>

export type TripPricingCreateTripPricingData = {
  requestBody: TripPricingCreate
}

export type TripPricingCreateTripPricingResponse = TripPricingPublic

export type TripPricingListTripPricingData = {
  ticketType?: string | null
  tripId?: string | null
}

export type TripPricingListTripPricingResponse = Array<TripPricingPublic>

export type TripPricingGetTripPricingData = {
  tripPricingId: string
}

export type TripPricingGetTripPricingResponse = TripPricingPublic

export type TripPricingUpdateTripPricingData = {
  requestBody: TripPricingUpdate
  tripPricingId: string
}

export type TripPricingUpdateTripPricingResponse = TripPricingPublic

export type TripPricingDeleteTripPricingData = {
  tripPricingId: string
}

export type TripPricingDeleteTripPricingResponse = void

export type TripPricingListPublicTripPricingData = {
  tripId: string
}

export type TripPricingListPublicTripPricingResponse = Array<TripPricingPublic>

export type TripsReadTripsData = {
  limit?: number
  skip?: number
}

export type TripsReadTripsResponse = TripsPublic

export type TripsCreateTripData = {
  requestBody: TripCreate
}

export type TripsCreateTripResponse = TripPublic

export type TripsReadTripData = {
  tripId: string
}

export type TripsReadTripResponse = TripPublic

export type TripsUpdateTripData = {
  requestBody: TripUpdate
  tripId: string
}

export type TripsUpdateTripResponse = TripPublic

export type TripsDeleteTripData = {
  tripId: string
}

export type TripsDeleteTripResponse = TripPublic

export type TripsReadTripsByMissionData = {
  limit?: number
  missionId: string
  skip?: number
}

export type TripsReadTripsByMissionResponse = TripsPublic

export type TripsReadPublicTripsData = {
  accessCode?: string | null
  limit?: number
  skip?: number
}

export type TripsReadPublicTripsResponse = TripsPublic

export type TripsReadPublicTripData = {
  accessCode?: string | null
  tripId: string
}

export type TripsReadPublicTripResponse = TripPublic

export type TripsImportTripFromYamlData = {
  formData: Body_trips_import_trip_from_yaml
}

export type TripsImportTripFromYamlResponse = TripPublic

export type UsersReadUsersData = {
  limit?: number
  skip?: number
}

export type UsersReadUsersResponse = UsersPublic

export type UsersCreateUserData = {
  requestBody: UserCreate
}

export type UsersCreateUserResponse = UserPublic

export type UsersReadUserMeResponse = UserPublic

export type UsersDeleteUserMeResponse = Message

export type UsersUpdateUserMeData = {
  requestBody: UserUpdateMe
}

export type UsersUpdateUserMeResponse = UserPublic

export type UsersUpdatePasswordMeData = {
  requestBody: UpdatePassword
}

export type UsersUpdatePasswordMeResponse = Message

export type UsersRegisterUserData = {
  requestBody: UserRegister
}

export type UsersRegisterUserResponse = UserPublic

export type UsersReadUserByIdData = {
  userId: string
}

export type UsersReadUserByIdResponse = UserPublic

export type UsersUpdateUserData = {
  requestBody: UserUpdate
  userId: string
}

export type UsersUpdateUserResponse = UserPublic

export type UsersDeleteUserData = {
  userId: string
}

export type UsersDeleteUserResponse = Message

export type UtilsTestEmailData = {
  emailTo: string
}

export type UtilsTestEmailResponse = Message

export type UtilsHealthCheckResponse = {
  [key: string]: string
}

export type UtilsGetUsStatesResponse = {
  [key: string]: Array<{
    [key: string]: string
  }>
}
