"""add_discount_codes_table

Revision ID: 1f3389205a66
Revises: d470d2a8cd29
Create Date: 2025-10-27 00:52:21.932967

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1f3389205a66'
down_revision = 'd470d2a8cd29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('boat', 'provider_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('boat', 'provider_location',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('boat', 'provider_address',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('boat', 'provider_address',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('boat', 'provider_location',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('boat', 'provider_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
