"""remove_state_from_jurisdiction

Revision ID: 26a5becb4e42
Revises: 2213cc00582c
Create Date: 2026-01-28 13:04:58.674482

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '26a5becb4e42'
down_revision = '2213cc00582c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the state column from jurisdiction table
    op.drop_column('jurisdiction', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate the state column (for rollback purposes)
    # Note: State will need to be populated from location.state after rollback
    op.add_column('jurisdiction', sa.Column('state', sa.VARCHAR(length=100), nullable=True))
    # Populate state from location.state
    op.execute(
        "UPDATE jurisdiction SET state = (SELECT state FROM location WHERE location.id = jurisdiction.location_id)"
    )
    # Make it NOT NULL after populating
    op.alter_column('jurisdiction', 'state', nullable=False)
    # ### end Alembic commands ###
