"""add_discount_code_id_to_booking

Revision ID: 2baf1908bed6
Revises: 1f3389205a66
Create Date: 2025-10-27 01:03:43.840627

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2baf1908bed6'
down_revision = '1f3389205a66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('discount_code_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'booking', 'discountcode', ['discount_code_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_column('booking', 'discount_code_id')
    # ### end Alembic commands ###
