"""update_user_full_name_max_length

Revision ID: 54f24cc0ec62
Revises: fc9bc6393e19
Create Date: 2026-01-27 02:51:36.881573

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '54f24cc0ec62'
down_revision = 'fc9bc6393e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First, truncate any existing full_name values longer than 64 characters
    op.execute(
        "UPDATE \"user\" SET full_name = LEFT(full_name, 64) WHERE full_name IS NOT NULL AND LENGTH(full_name) > 64"
    )

    # Now alter the column size
    op.alter_column('user', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'full_name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
