"""booking_items_add_trip_merch_ref

Revision ID: 5934af3872af
Revises: fbd944cf2209
Create Date: 2025-08-14 01:43:20.485162

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5934af3872af'
down_revision = 'fbd944cf2209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
