"""add_trip_merchandise_id_to_bookingitem

Revision ID: d470d2a8cd29
Revises: 5934af3872af
Create Date: 2025-08-30 19:51:54.469009

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd470d2a8cd29'
down_revision = '5934af3872af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookingitem', sa.Column('trip_merchandise_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'bookingitem', 'tripmerchandise', ['trip_merchandise_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookingitem', type_='foreignkey')
    op.drop_column('bookingitem', 'trip_merchandise_id')
    # ### end Alembic commands ###
