"""Add trip pricing and merchandise tables

Revision ID: fbd944cf2209
Revises: add_missing_enum_values
Create Date: 2025-08-13 23:51:04.942269

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fbd944cf2209'
down_revision = 'add_missing_enum_values'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
